version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/go:1.15.8

jobs:
  make_lib:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libboost-all-dev
      - run: sudo apt-get install libtbb-dev
      - run: sudo apt install libcrypto++-dev
      - run: make -f makefile_linux
      - store_artifacts:
          path: libmhasher.so

workflows:
  version: 2
  make_lib_and_test:
    jobs:
      - make_lib
